# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  jwtauth:
    image: jwtauth
    build:
      context: .
      dockerfile: JwtAuth/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5188:5188
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
